# Generated by Django 4.1.6 on 2023-02-16 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsFactory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=50, verbose_name='страна')),
                ('city', models.CharField(max_length=50, verbose_name='город')),
                ('street', models.CharField(max_length=50, verbose_name='улица')),
                ('home_number', models.PositiveSmallIntegerField(verbose_name='номер дома')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты завода',
            },
        ),
        migrations.CreateModel(
            name='ProductsFactory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('product_model', models.CharField(max_length=50, verbose_name='Модель')),
                ('date_released', models.DateField(verbose_name='Дата выхода на рынок')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукция завода',
            },
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('debt_to_supplier', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, verbose_name='Задолженность перед поставщиком')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.contactsfactory', verbose_name='Контакты')),
                ('products', models.ManyToManyField(to='factory.productsfactory', verbose_name='Продукция')),
            ],
            options={
                'verbose_name': 'Завод',
                'verbose_name_plural': 'Заводы',
            },
        ),
    ]
