# Generated by Django 4.1.6 on 2023-02-16 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factory',
            name='debt_to_supplier',
        ),
    ]
