# Generated by Django 4.1.6 on 2023-02-18 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0002_remove_factory_debt_to_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='contacts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='factory.contactsfactory', verbose_name='Контакты'),
        ),
    ]
