# Generated by Django 4.1.6 on 2023-02-16 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsRN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=50, verbose_name='страна')),
                ('city', models.CharField(max_length=50, verbose_name='город')),
                ('street', models.CharField(max_length=50, verbose_name='улица')),
                ('home_number', models.PositiveSmallIntegerField(verbose_name='номер дома')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты розничной сети',
            },
        ),
        migrations.CreateModel(
            name='ProductsRN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('product_model', models.CharField(max_length=50, verbose_name='Модель')),
                ('date_released', models.DateField(verbose_name='Дата выхода на рынок')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукция розничной сети',
            },
        ),
        migrations.CreateModel(
            name='RetailNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('debt_to_supplier', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, verbose_name='Задолженность перед поставщиком')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail_network.contactsrn', verbose_name='Контакты')),
                ('products', models.ManyToManyField(to='retail_network.productsrn', verbose_name='Продукция')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.factory', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Розничная сеть',
                'verbose_name_plural': 'Розничные сети',
            },
        ),
    ]
