# Generated by Django 4.1.6 on 2023-02-18 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail_network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailnetwork',
            name='contacts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='retail_network.contactsrn', verbose_name='Контакты'),
        ),
    ]
